#version: "3.8"
services:
  unbound:
    build:
      context: .
      dockerfile: 1.22.0/Dockerfile
      #container_name: unbound1
    restart: unless-stopped
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    environment:
      - TZ=Europe/Berlin
    volumes:
      - unbound1:/opt/unbound/etc/unbound
      - data1:/data
    hostname: unbound1
    networks:
      - dnsnet1
volumes:
  unbound1: {}
networks:
  dnsnet1: {}
