version: "3.8"
services:
  unbound1:
    image: pedantic/unbound
    container_name: unbound
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5335:53/tcp
      - 5335:53/udp
     environment:
      - TZ=Europe/Berlin
    volumes:
      - unbound:/opt/unbound/etc/unbound
    hostname: unbound1
    networks:
      - dnsnet1
volumes:
  unbound1: {}
networks:
  dnsnet1: {}
